---
File_prefix: 2010-11-19-
Base_properties_file: default.properties

PROBLEM_FILE:
  - exampleproblems/hgen1-v250-s671234684.cnf
  - exampleproblems/uf50-0456.cnf
  
WORLD_DIMENSIONS:
  - 1,1
  
CARRYING_CAPACITY:
  - 4000
  - 8000
  - 9000
  - 18000
  
MIGRATION_PROBABILITY:
  - 0
  
MIGRATION_DISTANCE:
  - 0
  
AVERAGE_MUTATIONS:
  - 1
  - 2
  
GEOGRAPHY_TYPE:
  - locality.geography.UniformGeography
  
STARTING_POPULATION:
  - EVERYWHERE