---
File_prefix: FirstRuns
Base_properties_file: default.properties

PROBLEM_FILE:
  - exampleproblems/hgen1-v250-s671234684.cnf
  - exampleproblems/uf50-0456.cnf
  
WORLD_DIMENSIONS:
  - 30, 30
  - 20, 20
  - 10, 10
  
CARRYING_CAPACITY:
  - 20
  - 10
  
GEOGRAPHY_TYPE:
  - landscapeEC.locality.geography.FractalGeography
  - landscapeEC.locality.geography.ManhattanDistanceGeography
  
GEOGRAPHY_NOISE_STRENGTH:
  - 0
  - 1
  
MIGRATION_PROBABILITY:
  - 0.1
  - 0.15
  
MIGRATION_DISTANCE:
  - 1
  - 2